### ISSUE TITLE
FileNotFoundError when running csrmesh

### ISSUE THREAD

**Issue by kajaba** [nkaminski/csrmesh#26]
Hello I recently got a new raspy pi and I decieded to give another try with move blinds.
But after python setup.py install and after runing 
csrmesh-cli move --pin 1985 --dest F6:4E:48:5C:06:84 --objid 0 --position 0
I got this error. I am not very familiar with python, so please help me :)

[+] Connecting to device F6:4E:48:5C:06:84
Traceback (most recent call last):
  File "/usr/local/bin/csrmesh-cli", line 4, in <module>
    __import__('pkg_resources').run_script('csrmesh==0.9.1', 'csrmesh-cli')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.7/dist-packages/csrmesh-0.9.1-py3.7.egg/EGG-INFO/scripts/csrmesh-cli", line 33, in <module>
    res = cm.movecontroller.set_position(args.dest, args.pin, args.position, args.objid, True)
  File "/usr/local/lib/python3.7/dist-packages/csrmesh-0.9.1-py3.7.egg/csrmesh/movecontroller.py", line 11, in set_position
    return gatt.send_packet(dest, 0x0021, packet, debug)
  File "/usr/local/lib/python3.7/dist-packages/csrmesh-0.9.1-py3.7.egg/csrmesh/gatt.py", line 30, in send_packet
    device=connect(dest.split(','), debug)
  File "/usr/local/lib/python3.7/dist-packages/csrmesh-0.9.1-py3.7.egg/csrmesh/gatt.py", line 13, in connect
    device = btle.Peripheral(mac, addrType=btle.ADDR_TYPE_PUBLIC)
  File "/usr/local/lib/python3.7/dist-packages/bluepy-1.3.0-py3.7.egg/bluepy/btle.py", line 391, in __init__
    self._connect(deviceAddr, addrType, iface)
  File "/usr/local/lib/python3.7/dist-packages/bluepy-1.3.0-py3.7.egg/bluepy/btle.py", line 426, in _connect
    self._startHelper(iface)
  File "/usr/local/lib/python3.7/dist-packages/bluepy-1.3.0-py3.7.egg/bluepy/btle.py", line 284, in _startHelper
    preexec_fn = preexec_function)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/dist-packages/bluepy-1.3.0-py3.7.egg/bluepy/bluepy-helper': '/usr/local/lib/python3.7/dist-packages/bluepy-1.3.0-py3.7.egg/bluepy/bluepy-helper'

**Comment by nkaminski** [comment]
This looks like a bluepy issue. If you reinstall bluepy in a python virtualenv, are any errors printed during the build/install process?
